# -*- coding: utf-8 -*-
"""for.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-UtB1dQSGhRFYAz1oJyiIHPERlm51QF4

**Exercício** **1**
"""

#Faça um programa que leia 5 números e informe o maior.

maior_numero = float('-inf') #Esse -inf é para não aceitar números infinitos
for i in range(5):
  numero = float(input(f"Digite o {i+1}º número: "))
  if numero > maior_numero:
    maior_numero = numero #O maior número recebe o valor da variavel numero
#Final do bloco
print(f"O maior número digitado é: {maior_numero}")

"""**Exercício** **2**"""

#Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 11 produzem restos igual a 2.
for numero in range(1000,2001):
  if numero % 11 == 2:
    print(numero)

"""**Exercício** **3**"""

#Faça um programa que receba um número e usando laços de repetição  calcule e mostre a tabuada desse número.

numero = int(input("Digite um número que você não sabe a tabuada"))

print(f"Tabuada de {numero}")
for contador in range(1,11):
  resultado = numero * contador
  print(f"{numero} x {contador} = {resultado}")

"""**Exercício** **4**"""

#Faça um programa que imprima na tela os número de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.

for i in range(1,21):
  print(i)

print(list(range(1,21)))

"""**Exercício** **5**"""

#Faça um programa que leia 5 números e informe a soma e a média dos números

soma = 0

for n in range(5):
  numero = float(input(f"Coloque um número:"))
  soma += numero

media =  soma / 5

print(f"A soma dos números é: {soma}")
print(f"A média é: {media}")

"""**Exercício** **6**"""

#Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição.

for contador in range(1,11):
  print(f"Número atual {contador}")

  for num in range(1,11):
    print(f"{contador} x {num} = {num * contador}")

"""**Exercício** **7**"""

#Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.

for i in range(1,51):
  if i % 2 !=0:
   print(i)

"""**Exercício** **8**"""

#Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.

n1 = int(input('Digite um número'))
n2 = int(input('Digite outro número'))

for i in range(n1 + 1, n2): #O 1 vai mostrar os números entre o n1 e n2
  print(i)

"""**Exercício** **9**"""

#Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor
#mostre na tela uma mensagem contendo em quanto foi superado o faturamento.

lojaA = 0
lojaB = 54000

for cliente in range(5):
  gasto = float(input(f"digite o gasto do cliente {cliente+1}"))
  lojaA += gasto

if lojaA > lojaB:
  print(f"A loja A superou o faturamento da loja B com um valor arrecadado maior de R$ {lojaA - lojaB}")
elif lojaB>lojaA:
  print(f"A loja B superou o faturamento da loja A com um valor arrecadado maior de R$ {lojaB - lojaA}")
else:
  print(f"As duas lojas arrecadaram o mesmo valor de R$ {lojaA}")

"""**Exercício** **10**"""

#Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares.

numeros_pares = 0
numeros_impares = 0

for i in range(10):
  numero = int(input(f"Coloque o {i} numro inteiro:"))

  if numero % 2 == 0:
    numeros_pares += 1
  else:
    numeros_impares += 1

print(f"A quantidade de números pares é {numeros_pares} e a quantidade de números impares é {numeros_impares}")

"""**Exercício** **11**"""

#Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que:
#Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00;
#Em 1996 recebeu aumento de 1,5% sobre seu salário inicial;
#A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o
#salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.

salario = float(input("Digite o salário inicial do funcionário:"))
percentual = 0.015

for i in range (1996,2025):
  aumento = salario * percentual
  salario += aumento
  percentual *= 2
  print(f"Salário em {i} = {salario: .2f}")

"""**Exercício** **12**"""

#Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.

for contador in range(999):
  numero = int(input("Coloque um número entre 0 e 10"))
  if numero > 0 and numero <= 10:
    print("válido")
    break
else:
    print("Inválido")

"""**Exercício** **13**"""

#Uma loja tem tem uma política de descontos de acordo com o valor da compra do cliente. Os descontos começam acima dos R$500. A cada 100
#reais acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até 25%.
#Por exemplo: R$500 = 1% || R$600,00 = 2% … etc…
#Faça um programa que exiba essa tabela de descontos no seguinte formato:
#Valordacompra – porcentagem de desconto – valor final

valor = float(input("Digite o valor do produto: R$"))
contador = 2

if valor >= 600 and contador:
  reduzido = valor - 500
  if reduzido >= 100 or contador <=24:
    for x in range(999):
      contador += 1
      reduzido -=100
      if reduzido < 100 or contador == 24:
        break

porcentagem = contador / 100
desconto = valor * porcentagem
final = valor - desconto
print(f"O produto de R${valor:.2f} ficará a partir de ")

#---dar uma olhada

"""**Exercício** **14**"""

#Faça um programa que receba a idade de 15 pessoas e que calcule e mostre:
#a) A quantidade de pessoas em cada faixa etária;
#b) A percentagem de pessoas na primeira e na última faixa etária, com relação ao total de pessoas:
# Até 15 anos
# De 16 a 30 anos
# De 31 a 45 anos
# De 46 a 60 anos
# Acima de 61 anos

ate15 = 0
de16a30 = 0
de31a45 = 0
de46a60 = 0
acimade61 = 0

for pessoa in range(15):
  idade = int(input(f"Digite a idade da pessoa {pessoa+1}:"))
  if idade <= 15:
    ate15 += 1
  elif 16 <= idade <= 30:
    de16a30 += 1
  elif 31 <= idade <= 45:
    de31a45 += 1
  elif 46 <= idade <= 60
    de46a60 += 1
  else:
    acimade61

print(f"O produto de R$ {}")

"""**Exercício** **15**"""

#Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem.

base = float(input("Coloque um numero para ser a base"))
expoente = float(input("Coloque um numero para ser o expoente"))
resultado = 1

for i in range(expoente):
  if base == 1:
    result = base
  else:
    result *= base

print(f"Resultado {result}")

"""**Exercício** **16**"""

#Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário. O programa deverá mostrar também
#o número de divisões que ele executou para encontrar os números primos. Serão avaliados o funcionamento, o estilo e o número de testes (divisões) executados.

n = int(input("Digite um número:"))

for numeroTestado in range(2,n):
  for numeroDivisor in range (numeroTestado):
    print(f"{numeroTestado}/{numeroDivisor} = {numeroTestado/numeroDivisor} com o resto {numeroTestado%(numeroDivisor+1)}")
    if numeroTestado % (numeroDivisor+1) == 0:
      if 1 != numeroDivisor+1 != numeroTestado:
        print("Não é primo")
        break
      elif numeroDivisor+1 == numeroTestado:
        print("Número primo")